baseurl = "http://www.example.com"
title = "Task 2 Project Work"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Project Work Task 2 - Static Websites"
    description = "Static Website"
    keywords = "blog,developer,personal"
    info = "Linda Feichtner & Markus Fritz"
    avatarurl = "images/fhjoanneumgraz.png"
    footercontent = "Content Strategy / FH Joanneum Graz"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Questions - Task 2"
            weight = 1
            url = "posts/"

            [[languages.en.menu.main]]
            name = "About us"
            weight = 2
            url = "about/about/"

    [languages.pt-br]

        [languages.pt-br.params]
            author = "Linda Feichtner & Markus Fritz"
            info = "Linda Feichtner und Markus Fritz"
            description = "Task 2 - Static Website - Backend Development"
            keywords = "static website, website, project"
            footercontent = "FH Joanneum"